Slander/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('authapp.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('mainapp.urls')),
]


urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from django.template import RequestContext
from . import views
app_name = 'mainapp'

urlpatterns = [
    path('', views.Index.as_view(), name='main_page'),
    path('artists/', views.ArtistsList.as_view(), name='artists'),
    path('albums/', views.AlbumsList.as_view(), name='albums'),
    path('tracks/', views.TrackList.as_view(), name='tracks'),
    path("search/", views.MainSearch.as_view(), name='main-search'),
    path("search/artists/", views.ArtistSearch.as_view(), name='artist-search'),
    path("search/albums/", views.AlbumSearch.as_view(), name='album-search'),
    path("search/tracks/", views.TrackSearch.as_view(), name='track-search'),
    path("filter/artists/", views.ArtistFilter.as_view(), name='artist-filter'),
    path("filter/albums/", views.AlbumFilter.as_view(), name='album-filter'),
    path("filter/tracks/", views.TrackFilter.as_view(), name='track-filter'),
    path("sorting/artists/", views.SortingArtists.as_view(), name='sort-artists'),
    path("sorting/albums/", views.SortingAlbums.as_view(), name='sort-albums'),
    path("sorting/tracks/", views.SortingTracks.as_view(), name='sort-tracks'),
    path('artists/post', views.ArtistCreate.as_view(), name='artist_post'),
    path('albums/post', views.AlbumCreate.as_view(), name='album_post'),
    path('tracks/post', views.TrackCreate.as_view(), name='track_post'),
    path('genre/post', views.AddGenre.as_view(), name='add-genre'),
    path('artists/<slug:slug>/', views.ArtistDetail.as_view(), name='artist_detail'),
    path('albums/<slug:slug>/', views.AlbumDetail.as_view(), name='album_detail'),
    path('tracks/<slug:slug>/', views.TrackDetail.as_view(), name='track_detail'),
    path("artists/<int:pk>/comment/", views.AddCommenttoArtist.as_view(), name="add_comment_to_artist"),
    path("artists/<int:id>/update-rating", views.AddRating.as_view(), name='update-rating-to-artist'),
    path("artists/<int:pk>/artist-delete/", views.ArtistDelete.as_view(), name='artist_delete'),
    path("artists/<int:pk>/artist-update/", views.ArtistUpdate.as_view(), name='artist_update'),
    path("albums/<int:pk>/comment/", views.AddCommenttoAlbum.as_view(), name="add_comment_to_album"),
    path("albums/<int:id>/update-rating", views.AddRating.as_view(), name='update-rating-to-album'),
    path("albums/<int:pk>/album-delete/", views.AlbumDelete.as_view(), name='album_delete'),
    path("albums/<int:pk>/album-update/", views.AlbumUpdate.as_view(), name='album_update'),
    path("tracks/<int:pk>/comment/", views.AddCommenttoTrack.as_view(), name="add_comment_to_track"),
    path("tracks/<int:id>/update-rating", views.AddRating.as_view(), name='update-rating-to-track'),
    path("tracks/<int:pk>/track-delete/", views.TrackDelete.as_view(), name='track_delete'),
    path("tracks/<int:pk>/track-update/", views.TrackUpdate.as_view(), name='track_update'),
]


def handler404(request, *args, **argv):
    response = render('404_login_required.html', {}, context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request, *args, **argv):
    response = render('500.html', {}, context_instance=RequestContext(request))
    response.status_code = 500
    return response


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/forms.py
from django import forms
from .models import Album, Rating, Artist, Image, Comment, Track, Genre
from urllib.parse import urlparse
import requests
from PIL import Image as Img
from urllib import request
from django.core.files.base import ContentFile


class ImageUploadForm(forms.ModelForm):
    """
    Валидация ссылки и уникальности заполнение полей ввода
    !не выводятся ошибки формы кроме error_message со вьюхи
    """
    prefix = 'Image'

    class Meta:
        model = Image
        fields = ['image_url', 'original']

    def clean(self):
        cleaned_data = self.cleaned_data
        if cleaned_data['image_url'] and cleaned_data['original']:
            raise forms.ValidationError('Заполните только одно поле ввода!')
        if cleaned_data['image_url']:  # валидация и загрузка картинки по URL
            try:
                resp = requests.get(cleaned_data['image_url'], stream=True).raw
            except requests.exceptions.RequestException as e:
                raise forms.ValidationError('Нерабочая ссылка!')
            try:
                img = Img.open(resp)
            except IOError:
                raise forms.ValidationError('Невозможно открыть файл картинки!')
        return cleaned_data

    def save(self, force_insert=False, force_update=False, commit=True):
        cleaned_data = self.cleaned_data
        original = super(ImageUploadForm, self).save(commit=False)
        if cleaned_data['image_url']:
            image_url = self.cleaned_data['image_url']
            image_name = urlparse(cleaned_data['image_url']).path.split('/')[-1].lower()
            response = request.urlopen(image_url)
            original.original.save(image_name, ContentFile(response.read()), save=False)
        if commit:
            original.save()
        return original


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    class Meta:
      model = Rating
      fields = ('ip', 'value', 'artist')


class GenreForm(forms.ModelForm):
    """Форма добавления жанра"""
    class Meta:
      model = Genre
      fields = ['name']


class ArtistForm(forms.ModelForm):
    """Форма создания статьи с артистом"""
    prefix = 'Artist'
    GENRE_CHOICES = Genre().get_genre_choices()
    genres = forms.MultipleChoiceField(label='Жанры', required=False,
                                       widget=forms.CheckboxSelectMultiple(),
                                       choices=GENRE_CHOICES,)

    class Meta:
        model = Artist
        fields = ['name', 'biography', 'genres']


class AlbumForm(forms.ModelForm):
    """Форма создания статьи с альбомом"""
    prefix = 'Album'
    GENRE_CHOICES = Genre().get_genre_choices()
    genres = forms.MultipleChoiceField(label='Жанры', required=False,
                                       widget=forms.CheckboxSelectMultiple(),
                                       choices=GENRE_CHOICES,)
    published_date = forms.DateField(label='Дата релиза', widget=forms.DateInput(format='%d-%m-%Y',
                                     attrs={'type': 'date'}))

    class Meta:
        model = Album
        fields = ['title', 'description', 'artist', 'published_date', 'genres', 'url']


class TrackForm(forms.ModelForm):
    """Форма создания статьи с песней"""
    prefix = 'Track'
    GENRE_CHOICES = Genre().get_genre_choices()
    genres = forms.MultipleChoiceField(label='Жанры', required=False,
                                       widget=forms.CheckboxSelectMultiple(),
                                       choices=GENRE_CHOICES,)

    class Meta:
        model = Track
        fields = ['title', 'album', 'other_artist', 'description', 'genres', 'url']


class CommentForm(forms.ModelForm):
    """Форма добавления комментария"""
    prefix = 'Comment'

    class Meta:
        model = Comment
        fields = ["comment_text"]

mainapp/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.base import View
from django.template.defaultfilters import slugify
from unidecode import unidecode
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse
from django.urls import reverse_lazy


from .models import Artist, Album, Track, Comment, Rating
from .models import Genre as GenreModel
from .forms import ArtistForm, AlbumForm, ImageUploadForm, CommentForm, TrackForm, GenreForm


class Index(TemplateView):
    """
    Отображение главной страницы
    """
    template_name = 'index.html'


class Genre:
    """Отображает все жанры"""

    @staticmethod
    def get_genres():
        return GenreModel.objects.all()


class ArtistsList(Genre, ListView):
    """Страница cо статьями артистов"""
    model = Artist
    queryset = Artist.objects.filter(draft=False)
    template_name = 'artists.html'
    paginate_by = 5


class AlbumsList(Genre, ListView):
    """Страница cо статьями альбомов"""
    model = Album
    queryset = Album.objects.filter(draft=False)
    template_name = 'albums.html'
    paginate_by = 3


class TrackList(Genre, ListView):
    """Страница cо статьями песен"""
    model = Track
    queryset = Track.objects.filter(draft=False)
    template_name = 'tracks.html'
    paginate_by = 5


class ArtistDetail(Genre, DetailView):
    """Статья артиста"""
    model = Artist
    queryset = Artist.objects.filter(draft=False)
    template_name = 'artist_detail.html'

    def get_context_data(self, *args, **kwargs):
        """Отображает комментарии в статье артиста"""
        context = super().get_context_data(*args, **kwargs)
        form = CommentForm()
        context["form"] = form
        return context


class AlbumDetail(Genre, DetailView):
    """Статья альбома"""
    model = Album
    queryset = Album.objects.filter(draft=False)
    template_name = 'album_detail.html'

    def get_context_data(self, *args, **kwargs):
        """Отображает комментарии в статье альбома"""
        context = super().get_context_data(*args, **kwargs)
        form = CommentForm()
        context["form"] = form
        return context


class TrackDetail(Genre, DetailView):
    """Статья песни"""
    model = Track
    queryset = Track.objects.filter(draft=False)
    template_name = 'track_detail.html'

    def get_context_data(self, *args, **kwargs):
        """Отображает комментарии в статье песни"""
        context = super().get_context_data(*args, **kwargs)
        form = CommentForm()
        context["form"] = form
        return context


class AddRating(View):
    """Добавление рейтинга статье с артистом/альбомом/песней"""

    @staticmethod
    def get_client_ip(request):
        """Вычисляет ip, для того чтобы статье нельзя было поставить больше одного лайка с одного ip"""
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip    

    def update_rate(self, obj_type, id):
        """Пересчитывает рейтинг статьи"""
        obj = obj_type.objects.get(id=id)
        obj.rate = obj.calculate_rating()
        obj.save()
        return obj

    def post(self, request, id):
        """Определяет тип статьи и добавляет ей рейтинг"""
        if request.POST.get("obj-type") == 'artist':
            Rating.objects.update_or_create(ip=self.get_client_ip(request),  value=int(request.POST.get("value")),
                                            artist_id=id)
            obj = self.update_rate(obj_type=Artist, id=id)
            return redirect(obj.get_absolute_url())
        elif request.POST.get("obj-type") == 'album':
            Rating.objects.update_or_create(ip=self.get_client_ip(request),  value=int(request.POST.get("value")),
                                            album_id=id)
            obj = self.update_rate(obj_type=Album, id=id)
            return redirect(obj.get_absolute_url())
        elif request.POST.get("obj-type") == 'track':
            Rating.objects.update_or_create(ip=self.get_client_ip(request),  value=int(request.POST.get("value")),
                                            track_id=id)
            obj = self.update_rate(obj_type=Track, id=id)
            return redirect(obj.get_absolute_url())
        else:
            return HttpResponse(status=400)


class ArtistCreate(TemplateView):
    """Создает статью с артистом"""
    model = Artist
    template_name = 'artist_post.html'
    success_url = reverse_lazy('mainapp:artists')

    def get(self, request, *args, **kwargs):
        """Отображает формы"""
        if self.request.user.is_authenticated:
            context = super().get_context_data(*args, **kwargs)
            context["form"] = ArtistForm
            context["img_form"] = ImageUploadForm
            return self.render_to_response(context)
        else:
            return render(None, '404_login_required.html')
     
    def post(self, request, *args, **kwargs):
        """Проверяет наличие имени артиста в базе. Если такого артиста нет, то создает статью.
        Также создаёт статью если не загружено изображение"""
        artist_form = ArtistForm(request.POST)
        img_form = ImageUploadForm(request.POST, request.FILES)
        if artist_form.is_valid():
            if img_form.is_valid():
                img_of_artist = img_form.save()
                img_of_artist.save()
                artist_post = artist_form.save(commit=False)
                artist_post.user = self.request.user
                artist_post.save()
                artist_post.photo.add(img_of_artist)
                return redirect(artist_post.get_absolute_url())
            else:
                context = {'form': ArtistForm, "img_form": ImageUploadForm,
                           'error_message': 'Не удалось загрузить изображение'}
        else:
            query_res = Artist.objects.filter(name=self.request.POST.get("Artist-name"))
            if query_res:
                return render(request, self.template_name, {'form': ArtistForm, "img_form": ImageUploadForm,
                                                            'error_message': 'Данная статья уже существует'})
            else:
                return render(request, self.template_name, {'form': ArtistForm, "img_form": ImageUploadForm,
                                                            'error_message': 'Ошибка создания статьи'})
        return render(request, self.template_name, context)


class AlbumTrackCreateMixin(TemplateView):
    """Предок для создания статьи с альбомом/песней"""
    obj_model = None
    obj_form = None
    template_name = None
    success_url = None

    def get(self, request, *args, **kwargs):
        """Отображает формы"""
        if self.request.user.is_authenticated:
            context = super().get_context_data(*args, **kwargs)
            context["form"] = self.obj_form
            return self.render_to_response(context)
        else:
            return render(None, '404_login_required.html')

    def post(self, request, *args, **kwargs):
        """1)Проверяет наличие названия альбома/песни в базе. Если названия нет, то создает статью.
           2)При создании статьи с песней id артиста добавляется автоматически, исходя из альбома"""
        form = self.obj_form(request.POST)
        if form.is_valid():
            if self.obj_form == TrackForm:
                form.album = form.cleaned_data['album']
            else:
                form.artist = form.cleaned_data['artist']               
            obj_post = form.save(commit=False)
            obj_post.user = self.request.user
            if self.obj_form == TrackForm:
                obj_post.artist = obj_post.album.artist
            obj_post.save()
            return redirect(obj_post.get_absolute_url())
        else:
            if self.obj_form == TrackForm:
                q = 'Track-title'
            else:
                q = 'Album-title'
            query_res = self.obj_model.objects.filter(title=self.request.POST.get(q))
            if query_res:
                return render(request, self.template_name, {'form': form,
                                                            'error_message': 'Данная статья уже существует'})
            else:
                return render(request, self.template_name, {'form': form, 'error_message': 'Ошибка создания статьи'})
        

class AlbumCreate(AlbumTrackCreateMixin):
    """Создает статью с альбомом"""
    obj_model = Album
    obj_form = AlbumForm
    template_name = 'album_post.html'
    success_url = reverse_lazy('mainapp:albums')


class TrackCreate(AlbumTrackCreateMixin):
    """Создает статью с песней"""
    obj_model = Track
    obj_form = TrackForm
    template_name = 'track_post.html'
    success_url = reverse_lazy('mainapp:tracks')


class SearchMixin(Genre, ListView):
    """Предок для поиска отдельно статей с артистами, альбомами и песнями"""
    obj_model = None
    template_name = 'search_results.html'
    paginate_by = 4

    def get_queryset(self):
        """Формирует queryset для отображения на странице с результатами поиска"""
        if self.obj_model == Artist:
            return self.obj_model.objects.filter(name__icontains=self.request.GET.get("q"))
        else:
            return self.obj_model.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        """Необходимо для пагинации объектов queryset"""
        context = super().get_context_data(*args, **kwargs)
        query_name = self.request.GET.get("q")
        context["query_name"] = query_name
        context["q"] = f'q={query_name}&'

mainapp/templates/include/album-card.html
{% load static %}


<div class="card-list">
    {% for album in object_list %}
      <div class="card text-white bg-dark" style="max-width: 540px;min-width: 520px;" id="card">
        <div class="row g-0">
          <p class="html-widget">
            <span>
            {% if album.html %}
                {% autoescape off %}
                    {{ album.html }}
                {% endautoescape %}
            {% else %}
                <h9>Послушать альбом невозможно. <a href = "{% url 'mainapp:album_update' album.id %}">Необходимо добавить ссылку на альбом со Spotify или Яндекс.Музыка</a></h9>
            {% endif %}
            </span>
        </p>
          <div class="col-md-8">
            <div class="card-body" id="album-card-body">
              {% if album.html %}
                <p class="card-text">{{ album.description|truncatewords:20 }}</p>
                <h5 class="card-to-detail"><a href = "{{ album.get_absolute_url }}">Читать подробнее...</a></h5>
              {% else %}
                <h5 class="card-title"><a href = "{{ album.get_absolute_url }}">{{album.title}}</a></h5>
                <p class="card-text">{{ album.description|truncatewords:20 }}</p>
              {% endif %}
            </div>
            {% include 'include/album-likes.html' %}
            <div class="comments-album">
              <div class="comment-elem">{{album.get_quantity_comments}}</div>
              <div class="comment-elem"><a href="{{ album.get_absolute_url }}#comments"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-text" viewBox="0 0 16 16">
                <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                <path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
              </svg></a></div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
</div>

mainapp/templates/include/album-likes.html
<div class="likes-album">
    <div class="like-elem" id="thumb-up">
      <form action="{% url 'mainapp:update-rating-to-album' album.id %}" method='POST' name="update-rating">
        {% csrf_token %}
        <input type="hidden" value="1" name="value">
        <input type="hidden" value="{{ album.id }}" name="id">
        <input type="hidden" value="album" name="obj-type">
        <button type="submit" class="btn" id="btn-thumb-up"></button>
      </form>
    </div>
    
    <div class="like-elem">
      {{ album.rate }}
    </div>
    
    <div class="like-elem" id="thumb-down">
      <form action="{% url 'mainapp:update-rating-to-album' album.id %}" method='POST' name="update-rating">
        {% csrf_token %}
        <input type="hidden" value="-1" name="value">
        <input type="hidden" value="{{ album.id }}" name="id">
        <input type="hidden" value="album" name="obj-type">
        <button type="submit" class="btn" id="btn-thumb-down"></button>
      </form>
    </div>
  </div>

mainapp/templates/include/album-utils.html
<div class="d1" id="left-search">
    <form action="{% url 'mainapp:album-search' %}" accept-charset="utf-8" method="GET">
      <input type="text" placeholder="Поиск по альбомам" name="q" required="">
      <button type="submit"></button>
    </form>
</div>


<form action="{% url 'mainapp:album-filter' %}" method="get" name="filter">
    <div class="container" style="max-width: 210px">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <span class="navbar-brand">Поиск по жанрам</span>
        </nav>
        <hr></hr>
        <ul class="nav flex-column">
            {% for genre in view.get_genres %}
                <li class="nav-item">
                    <input type="checkbox" class="checked" name="genre" value="{{ genre.name}}">
                    <span class="span-editContent">{{ genre.name  }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
    <button class="btn btn-secondary filter-genre" type="submit">Найти</button>
</form>

<a href="{% url 'mainapp:add-genre' %}"><button type="submit" class="btn" id="btn-thumb-genre-add"></button></a>

<button type="button" class="btn btn-secondary" id="dropdownMenu2"><a href="{% url 'mainapp:album_post' %}">Добавить альбом</a></button>

<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
        Фильтр по рейтингу
    </button>
    <ul class="dropdown-menu">
        <li>
            <form action="{% url 'mainapp:sort-albums' %}" method="GET" name="rating">
                <input type="hidden" value="up-to-down" name="sort-type">
                <button class="dropdown-item" type="submit">По убыванию</button>
            </form>
        </li>
        <li>
            <form action="{% url 'mainapp:sort-albums' %}" method="GET" name="rating">
                <input type="hidden" value="down-to-up" name="sort-type">
                <button class="dropdown-item" type="submit">По возрастанию</button>
            </form>
        </li>
    </ul>
</div>

mainapp/templates/include/artist-likes.html
<div class="likes">
    <div class="like-elem" id="thumb-up">
      <form action="{% url 'mainapp:update-rating-to-artist' artist.id %}" method='POST' name="update-rating">
        {% csrf_token %}
        <input type="hidden" value="1" name="value">
        <input type="hidden" value="{{ artist.id }}" name="id">
        <input type="hidden" value="artist" name="obj-type">
        <button type="submit" class="btn" id="btn-thumb-up"></button>
      </form>
    </div>
    
    <div class="like-elem">
      {{ artist.rate }}
    </div>
    
    <div class="like-elem" id="thumb-down">
      <form action="{% url 'mainapp:update-rating-to-artist' artist.id %}" method='POST' name="update-rating">
        {% csrf_token %}
        <input type="hidden" value="-1" name="value">
        <input type="hidden" value="{{ artist.id }}" name="id">
        <input type="hidden" value="artist" name="obj-type">
        <button type="submit" class="btn" id="btn-thumb-down"></button>
      </form>
    </div>
  </div>

mainapp/templates/include/artist-utils.html
<div class="d1" id="left-search">
    <form action="{% url 'mainapp:artist-search' %}" accept-charset="utf-8" method="GET">
      <input type="text" placeholder="Поиск по артистам" name="q" required="">
      <button type="submit"></button>
    </form>
</div>


<form action="{% url 'mainapp:artist-filter' %}" method="get" name="filter">
    <div class="container" style="max-width: 210px">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <span class="navbar-brand">Поиск по жанрам</span>
        </nav>
        <hr></hr>
        <ul class="nav flex-column">
            {% for genre in view.get_genres %}
                <li class="nav-item">
                    <input type="checkbox" class="checked" name="genre" value="{{ genre.name}}">
                    <span class="span-editContent">{{ genre.name  }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
    <button class="btn btn-secondary filter-genre" type="submit">Найти</button>
</form>

<a href="{% url 'mainapp:add-genre' %}"><button type="submit" class="btn" id="btn-thumb-genre-add"></button></a>

<button type="button" class="btn btn-secondary" id="dropdownMenu2"><a href="{% url 'mainapp:artist_post' %}">Добавить артиста</a></button>



<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
        Фильтр по рейтингу
    </button>
    <ul class="dropdown-menu">
        <li>
            <form action="{% url 'mainapp:sort-artists' %}" method="GET" name="rating">
                <input type="hidden" value="up-to-down" name="sort-type">
                <button class="dropdown-item" type="submit">По убыванию</button>
            </form>
        </li>
        <li>
            <form action="{% url 'mainapp:sort-artists' %}" method="GET" name="rating">
                <input type="hidden" value="down-to-up" name="sort-type">
                <button class="dropdown-item" type="submit">По возрастанию</button>
            </form>
        </li>
    </ul>
</div>

mainapp/templates/include/track-likes.html
<div class="likes">
    <div class="like-elem" id="thumb-up">
      <form action="{% url 'mainapp:update-rating-to-track' track.id %}" method='POST' name="update-rating">
        {% csrf_token %}
        <input type="hidden" value="1" name="value">
        <input type="hidden" value="{{ track.id }}" name="id">
        <input type="hidden" value="track" name="obj-type">
        <button type="submit" class="btn" id="btn-thumb-up"></button>
      </form>
    </div>
    
    <div class="like-elem">
      {{ track.rate }}
    </div>
    
    <div class="like-elem" id="thumb-down">
      <form action="{% url 'mainapp:update-rating-to-track' track.id %}" method='POST' name="update-rating">
        {% csrf_token %}
        <input type="hidden" value="-1" name="value">
        <input type="hidden" value="{{ track.id }}" name="id">
        <input type="hidden" value="track" name="obj-type">
        <button type="submit" class="btn" id="btn-thumb-down"></button>
      </form>
    </div>
</div>

mainapp/templates/include/track-utils.html
<div class="d1" id="left-search">
    <form action="{% url 'mainapp:track-search' %}" accept-charset="utf-8" method="GET">
      <input type="text" placeholder="Поиск по трекам" name="q" required="">
      <button type="submit"></button>
    </form>
</div>


<form action="{% url 'mainapp:track-filter' %}" method="get" name="filter">
    <div class="container" style="max-width: 210px">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <span class="navbar-brand">Поиск по жанрам</span>
        </nav>
        <hr></hr>
        <ul class="nav flex-column">
            {% for genre in view.get_genres %}
                <li class="nav-item">
                <input type="checkbox" class="checked" name="genre" value="{{ genre.name}}">
                <span class="span-editContent">{{ genre.name  }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
    <button class="btn btn-secondary filter-genre" type="submit">Найти</button>
</form>

<a href="{% url 'mainapp:add-genre' %}"><button type="submit" class="btn" id="btn-thumb-genre-add"></button></a>

<button type="button" class="btn btn-secondary" id="dropdownMenu2"><a href="{% url 'mainapp:track_post' %}">Добавить трек</a></button>

<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
        Фильтр по рейтингу
    </button>
    <ul class="dropdown-menu">
        <li>
            <form action="{% url 'mainapp:sort-tracks' %}" method="GET" name="rating">
                <input type="hidden" value="up-to-down" name="sort-type">
                <button class="dropdown-item" type="submit">По убыванию</button>
            </form>
        </li>
        <li>
            <form action="{% url 'mainapp:sort-tracks' %}" method="GET" name="rating">
                <input type="hidden" value="down-to-up" name="sort-type">
                <button class="dropdown-item" type="submit">По возрастанию</button>
            </form>
        </li>
    </ul>
</div>